from backend.modules.query_controllers.query_controller import register_query_controller
from backend.modules.query_controllers.default.controller import DefaultQueryController

register_query_controller("default", DefaultQueryController)
