from backend.modules.query_controllers.example.controller import ExampleQueryController
from backend.modules.query_controllers.query_controller import register_query_controller

register_query_controller("default", ExampleQueryController)
