name: Build and publish truefoundry-frontend-docs-qa

on: workflow_dispatch

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build_container:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set repository name
        run: |
          echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")" >> $GITHUB_ENV

      - name: Set docker repo name
        run: |
          echo "repository name is $REPOSITORY_NAME"
          echo "DOCKER_REPO=truefoundrycloud/$REPOSITORY_NAME-docs-qa" >> $GITHUB_ENV

      - name: Docker login
        run: |
          docker login -u truefoundry -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.GITHUB_SHA }}
          cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache,mode=max
          build-args: VITE_SKIP_SENTRY_SOURCE_MAP=true VITE_USE_RELATIVE_BASE_URL=true
